@baseUrl = http://localhost:8000/api


###

# /AUTH

###
POST {{baseUrl}}/auth/register/ HTTP/1.1
Content-Type: application/json

{
    "username":"quan",
    "password":"1111",
    "email":"phhoangquan@gmail.com"
}

###
POST {{baseUrl}}/auth/login/ HTTP/1.1
Content-Type: application/json

{   
    "email":"phhoangquan@gmail.com",
    "password":"1111"
}


###

POST {{baseUrl}}/token/ HTTP/1.1
Content-Type: application/json

{
    "email": "phhoangquan@gmail.com"
}
###
GET {{baseUrl}}/users/4/detail/ HTTP/1.1


###

POST {{baseUrl}}/get_images/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer <your_access_token>

{
    "username": "user1",
    "password": "1111"
}



###
POST {{baseUrl}}/folder/create/ HTTP/1.1
Content-Type: application/json

{
    "name": "folder1_1",
    "owner": "15",
    "parent": "1"


}

###
POST {{baseUrl}}/sync/save_drive_token/ HTTP/1.1
Content-Type: application/json

{
    "user_id": 1,
    "drive_email": "phhoangquan@gmail.com",
    "access_token": ""
}


###
POST {{baseUrl}}/sync/img/ HTTP/1.1
Content-Type: application/json

{
    "user_id": 1,
    "drive_email": "phhoangquan@gmail.com",
    "img_id":"1EKngeJRpyIW4Ca9Ybc2AoNAax7NqXew1",
    "img_name": "hello.jpg",
    "img_folder_id": 1

}

###
POST {{baseUrl}}/upload/img/ HTTP/1.1
Content-Type: application/json

{
    "user_id": 1,
    "img_file":"1EKngeJRpyIW4Ca9Ybc2AoNAax7NqXew1",
    "img_name": "hello.jpg",
    "img_folder_id": 1

}

###
GET {{baseUrl}}/1/1/images HTTP/1.1
